  deconz:
    container_name: deconz
    image: marthoc/deconz
    restart: unless-stopped
#    network_mode: host
    ports:
      - '80:80'
      - '443:443'
      - '5959:5959'
    volumes:
       - ./volumes/deconz/:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5959
      - DECONZ_VNC_PASSWORD=changeme
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
